//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Bernoulli.cpp
//  @ Date : 19.03.2018
//  @ Author : 
//
//


#include "Bernoulli.h"
#include <iostream>

using namespace std;

void Bernoulli::bernoulli(double p, int n, int k) {
    double ret=this->pNewton.calc(n,k)*this->pPower.power(p,k)*this->pPower.power(p,n-k);
    cout<<ret<<endl;
}

Bernoulli::Bernoulli() {

}

Bernoulli::~Bernoulli() {

}

