//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Factorial.cpp
//  @ Date : 19.03.2018
//  @ Author : 
//
//


#include "Factorial.h"

long double Factorial::factorial(int n) {


    if(n<2){
        return 1;
    }

    return factorial(n-1)*n;
}

