//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Newton.h
//  @ Date : 19.03.2018
//  @ Author : 
//
//


#if !defined(_NEWTON_H)
#define _NEWTON_H
#include "Factorial.h"

class Newton {
public:
	Newton();
	~Newton();
	long double calc(int n, int k);
private:
	int b;
	Factorial factorial;
};

#endif  //_NEWTON_H
