//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Newton.cpp
//  @ Date : 19.03.2018
//  @ Author : 
//
//


#include "Newton.h"

Newton::Newton() {

}

Newton::~Newton() {

}

long double Newton::calc(int n, int k) {

    this->b=n-k;

    double ret=this->factorial.factorial(n)/(this->factorial.factorial(k)*this->b);

    return ret;
}

