//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Power.cpp
//  @ Date : 19.03.2018
//  @ Author : 
//
//


#include "Power.h"

double Power::power(double n, int p) {

    for(int i=1;i<p;i++){
        n*=n;
    }

    return n;
}

